version: "3"
services: 
  mongodb:
    platform: linux/arm64
    image: mongo
    restart: always
    container_name: localmongo
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: jason
      MONGO_INITDB_ROOT_PASSWORD: password